"""ACI 318-25: Building Code Requirements for Structural Concrete."""

import typing as t

from ._concrete_material_properties import (
    Ec,
    alpha1,
    beta1,
    eps_cu,
    fct,
    fr,
    lambda_factor,
)
from ._reinforcement_material_properties import (
    Es,
    epsyd,
    fy_design,
    reinforcement_grade_props,
)
from ._flexure import (
    As_max_check,
    As_min_beam,
    As_min_slab,
    As_required,
    Mn_doubly_reinforced,
    Mn_singly_reinforced,
    eps_s_prime,
    eps_t_from_c,
    neutral_axis_depth,
    stress_block_depth_dr,
    stress_block_depth_sr,
)
from ._strength_reduction import (
    phi_bearing,
    phi_flexure,
    phi_shear,
    phi_torsion,
    section_classification,
)
from ._shear import (
    Av_min_per_s,
    Vc_detailed,
    Vc_simplified,
    Vn,
    Vs,
    check_cross_section,
    lambda_s,
    max_stirrup_spacing,
    shear_reinforcement_required,
)
from ._units import (
    FT_TO_MM,
    IN_TO_MM,
    KGM3_TO_PCF,
    KIP_TO_N,
    KSI_TO_MPA,
    LBF_TO_N,
    MM_TO_FT,
    MM_TO_IN,
    MPA_TO_KSI,
    MPA_TO_PSI,
    N_TO_KIP,
    N_TO_LBF,
    PCF_TO_KGM3,
    PSF_TO_KPA,
    PSF_TO_PA,
    PSI_TO_MPA,
)

__all__ = [
    'Ec',
    'alpha1',
    'beta1',
    'eps_cu',
    'fct',
    'fr',
    'lambda_factor',
    'Es',
    'epsyd',
    'fy_design',
    'reinforcement_grade_props',
    'phi_bearing',
    'phi_flexure',
    'phi_shear',
    'phi_torsion',
    'section_classification',
    'stress_block_depth_sr',
    'stress_block_depth_dr',
    'neutral_axis_depth',
    'eps_t_from_c',
    'eps_s_prime',
    'Mn_singly_reinforced',
    'Mn_doubly_reinforced',
    'As_min_slab',
    'As_min_beam',
    'As_max_check',
    'As_required',
    'lambda_s',
    'Vc_detailed',
    'Vc_simplified',
    'Vs',
    'Vn',
    'check_cross_section',
    'Av_min_per_s',
    'shear_reinforcement_required',
    'max_stirrup_spacing',
    'PSI_TO_MPA',
    'KSI_TO_MPA',
    'MPA_TO_PSI',
    'MPA_TO_KSI',
    'IN_TO_MM',
    'FT_TO_MM',
    'MM_TO_IN',
    'MM_TO_FT',
    'LBF_TO_N',
    'KIP_TO_N',
    'N_TO_LBF',
    'N_TO_KIP',
    'PSF_TO_PA',
    'PSF_TO_KPA',
    'PCF_TO_KGM3',
    'KGM3_TO_PCF',
]

__title__: str = 'ACI 318-25'
__year__: str = '2025'
__materials__: t.Tuple[str, ...] = ('concrete', 'reinforcement')
