"""ACI 318-19."""

import typing as t

from ._concrete_material_properties import (
    MINIMUM_STRESS_BLOCK_FC,
    Ec,
    alpha1,
    beta1,
    eps_c0,
    eps_cu,
    fr,
    lambda_factor,
)
from ._reinforcement_material_properties import (
    Es,
    epsyd,
    fy_design,
    reinforcement_grade_props,
)
from ._unit_conversions import (
    INCH_TO_MM,
    KIP_TO_N,
    KSI_TO_MPA,
    LB_FORCE_TO_N,
    LB_PER_CUBIC_FOOT_TO_KG_PER_CUBIC_METER,
    PSI_TO_MPA,
    in2_to_mm2,
    in3_to_mm3,
    in4_to_mm4,
    in_to_mm,
    kg_per_m3_to_pcf,
    kip_in_to_nmm,
    kip_to_n,
    ksi_to_mpa,
    lb_in_to_nmm,
    lb_to_n,
    mm2_to_in2,
    mm3_to_in3,
    mm4_to_in4,
    mm_to_in,
    mpa_to_ksi,
    mpa_to_psi,
    n_to_kip,
    n_to_lb,
    nmm_to_kip_in,
    nmm_to_lb_in,
    pcf_to_kg_per_m3,
    psi_to_mpa,
)

__all__ = [
    'Ec',
    'Es',
    'INCH_TO_MM',
    'KIP_TO_N',
    'KSI_TO_MPA',
    'LB_FORCE_TO_N',
    'LB_PER_CUBIC_FOOT_TO_KG_PER_CUBIC_METER',
    'MINIMUM_STRESS_BLOCK_FC',
    'PSI_TO_MPA',
    'alpha1',
    'beta1',
    'eps_c0',
    'eps_cu',
    'epsyd',
    'fr',
    'fy_design',
    'in2_to_mm2',
    'in3_to_mm3',
    'in4_to_mm4',
    'in_to_mm',
    'kg_per_m3_to_pcf',
    'kip_in_to_nmm',
    'kip_to_n',
    'ksi_to_mpa',
    'lambda_factor',
    'lb_in_to_nmm',
    'lb_to_n',
    'mm2_to_in2',
    'mm3_to_in3',
    'mm4_to_in4',
    'mm_to_in',
    'mpa_to_ksi',
    'mpa_to_psi',
    'n_to_kip',
    'n_to_lb',
    'nmm_to_kip_in',
    'nmm_to_lb_in',
    'pcf_to_kg_per_m3',
    'psi_to_mpa',
    'reinforcement_grade_props',
]

__title__: str = 'ACI 318-19'
__year__: str = '2019'
__materials__: t.Tuple[str] = ('concrete', 'reinforcement')
